    name: PHP Checker

    on: [push]

    jobs:
      build:
        name: Check
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
            with:
              fetch-depth: 0
          - name: PHP Syntax Checker (Lint) 7.2
            uses: StephaneBour/actions-php-lint@7.2
            with:
              dir: './'
          - name: PHP Syntax Checker (Lint) 7.4
            uses: StephaneBour/actions-php-lint@7.4
            with:
              dir: './'
          - name: PHP Syntax Checker (Lint) 7.2
            uses: StephaneBour/actions-php-lint@7.2
            with:
              dir: './dashboard'
          - name: PHP Syntax Checker (Lint) 7.4
            uses: StephaneBour/actions-php-lint@7.4
            with:
              dir: './dashboard'